### ISSUE TITLE
[FEATURE] userinfo and serverinfo commands

### ISSUE THREAD

**Issue by alexsurelee** [alexsurelee/VicBot#19]
`userinfo`: should print information about the user that called it. 

`userinfo 28752874827943`: should print information about the user with that id.

Information to print:
- Username
- Join date
- Permissions
- Join position
- Avatar

![example](https://user-images.githubusercontent.com/11603625/66007415-e07b7180-e50e-11e9-973c-ae50de8bd8dc.png)

`serverinfo`: should print information about the server the command was called in.

Information to print:
- Owner
- Creation date
- Channel count
- Member count
- Bot count

![example](https://user-images.githubusercontent.com/11603625/66007449-03a62100-e50f-11e9-82c7-ba5d46ebf4e4.png)

**Comment by alexsurelee** [comment]
Just go rip off Dyno

**Comment by GeordieR** [comment]
I'm interested in doing this, I might pick this up this week

**Comment by GeordieR** [comment]
I've created a branch on my fork for this. I'm just digging around the `discord.js` docs to see how to get the data needed. @alexsurelee would you be able to assign this ticket to me?

**Comment by GeordieR** [comment]
I got the userinfo working:

<img width="643" alt="Screen Shot 2019-10-04 at 10 16 30 AM" src="https://user-images.githubusercontent.com/25443532/66164856-0e3bf400-e690-11e9-8824-97d25639afb5.png">

**Comment by GeordieR** [comment]
Merged in https://github.com/alexsurelee/VicBot/pull/23.

This issue can now be closed

**Comment by NikiRakshu** [comment]
Hey joined Position is 0 always
in user info Command

**Comment by grogersxyz** [comment]
@NikiRakshu I haven't touched this code in a really long time sorry. I imagine it's an issue with the sorting of the array, or perhaps the permissions of the person who is trying to retrieve the array causing it to only return an array with the selected member.
